env:
  browser: true
  commonjs: true
  es2021: true
  jest/globals: true
extends:
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
  - 'plugin:prettier/recommended'
plugins:
  - 'jest'
  - 'prettier'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
